# FROM node:18-alpine

# # create a working directory
# WORKDIR /app

# # copy all files into the working dir
# COPY . .

# # install dependencies
# # RUN npm install

# EXPOSE 3000

# # run the app
# CMD [ "npm", "run", "dev" ]