version: '3.8'  # You might want to change this to '3' as '3.8' is obsolete

services:
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: "kejaprime"
      MINIO_ROOT_PASSWORD: "kejaprime123"
    volumes:
      - minio:/data  # Ensure this is correctly set

volumes:
  minio:  # Define the volume here
